./fit bmass ../RootFiles/AllCut/Data_KMuMu_AllCuts_v3.root 0
./fit bmass ../RootFiles/AllCut/Data_KMuMu_AllCuts_v3.root 1
./fit bmass ../RootFiles/AllCut/Data_KMuMu_AllCuts_v3.root 2
./fit bmass ../RootFiles/AllCut/Data_KMuMu_AllCuts_v3.root 3
./fit bmass ../RootFiles/AllCut/Data_KMuMu_AllCuts_v3.root 4
./fit bmass ../RootFiles/AllCut/Data_KMuMu_AllCuts_v3.root 5
./fit bmass ../RootFiles/AllCut/Data_KMuMu_AllCuts_v3.root 6
./fit bmass ../RootFiles/AllCut/Data_KMuMu_AllCuts_v3.root 7
./fit bmass ../RootFiles/AllCut/Data_KMuMu_AllCuts_v3.root 8
./fit bmass ../RootFiles/AllCut/Data_KMuMu_AllCuts_v3.root 9
./fit bmass ../RootFiles/AllCut/Data_KMuMu_AllCuts_v3.root 10
